app/books/forms.py
from flask import Flask

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, FileField, IntegerField
from wtforms.validators import DataRequired, Length, NumberRange



# =================================================================================================
# *** Books Form ***
class BooksForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), Length(2, 50)])
    description = StringField(
        "Description", validators=[DataRequired(), Length(2, 5000)]
    )
    image = FileField("Image", validators=[])
    pages = IntegerField(
        "Number Of Pages", validators=[DataRequired(), NumberRange(min=1)]
    )
    submit = SubmitField("Submit")

   

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap5

from flask_migrate import Migrate

from app.model import db
from app.config import config_options


def create_app(config_name="prd"):

    app = Flask(__name__)
    current_config = config_options[config_name]
    app.config.from_object(current_config)
    app.config.SQLALCHEMY_DATABASE_URI = current_config.SQLALCHEMY_DATABASE_URI


    db.init_app(app)
    migrate = Migrate(app, db)
    bootstrap = Bootstrap5(app)

    # app 
    from app.books import books_blueprint

    app.register_blueprint(books_blueprint)

    # -2 -> Home
    from app.home import home_blueprint

    app.register_blueprint(home_blueprint)


    return app

app/books/__init__.py
from flask import Blueprint

books_blueprint = Blueprint("books", __name__, url_prefix="/books")

from app.books import views

app/books/views.py
from flask import render_template, request, redirect, url_for, Blueprint

from werkzeug.utils import secure_filename
import os, datetime


# db
from app.model import db, Book

# books
from app.books import books_blueprint
from app.books.forms import BooksForm


# =================================================================================================
# *** List Books ***
@books_blueprint.route("/", endpoint="list")
def books_list():
    books = Book.query.all()
    return render_template("book_list.html", books=books)


# =================================================================================================
# *** Create Books ***
@books_blueprint.route("create", endpoint="create", methods=["GET", "POST"])
def books_create():
    form = BooksForm()
    date = datetime.datetime.now()
    default_image = "default_image.jpg"

    if request.method == "POST":
        if form.validate_on_submit():
            con_name = default_image

            if request.files.get("image"):
                image = form.image.data
                image_name = secure_filename(image.filename)
                con_name = f"{date.day}-{date.hour}-{date.minute}-{image_name}"
                image.save(os.path.join("static/uploads/", con_name))

            data = dict(request.form)
            book = Book(
                name=data["name"],
                description=data["description"],
                image=con_name,
                pages=data["pages"],
                created_at=date,
        
            )

            db.session.add(book)
            db.session.commit()

            return redirect(book.show_url)
    return render_template("create_book.html", form=form)


# =================================================================================================
# *** Update Books ***
@books_blueprint.route("<int:id>/update", endpoint="update", methods=["GET", "POST"])
def books_update(id):
    book = db.get_or_404(Book, id)
    if book is None:
        return redirect(url_for("books.list"))
    form = BooksForm(obj=book)
    date = datetime.datetime.now()
    default_image = "default_image.jpg"

    if request.method == "POST":
        if form.validate_on_submit():
            con_name = book.image or default_image

            if form.image.data:
                image = form.image.data
                image_name = secure_filename(image.filename)
                con_name = f"{date.day}-{date.hour}-{date.minute}-{image_name}"
                image.save(os.path.join("static/uploads/", con_name))

            book.name = form.name.data
            book.description = form.description.data
            book.image = con_name
            book.pages = form.pages.data
            db.session.commit()

            return redirect(book.show_url)

    return render_template("edit_book.html", form=form, book=book)


# =================================================================================================
# *** Show Details Books ***
@books_blueprint.route("<int:id>", endpoint="show")
def book_show(id):
    book = db.get_or_404(Book, id)
    return render_template("book_detail.html", book=book)


# =================================================================================================
# *** Delete Books ***
@books_blueprint.route("<int:id>/delete", endpoint="delete", methods=["POST"])
def book_delete(id):
    book = db.get_or_404(Book, id)
    if book is None:
        return redirect(url_for("books.list"))
    default_image = "default_image.jpg"

    if book.image and book.image != default_image:
        image_path = os.path.join("static/uploads/", book.image)
        if os.path.exists(image_path):
            os.remove(image_path)

    db.session.delete(book)
    db.session.commit()
    return redirect(url_for("books.list"))

app/home/__init__.py
from flask import Blueprint

home_blueprint = Blueprint("home", __name__, url_prefix="/")

from app.home import views

app/home/views.py
from flask import render_template, request, redirect, url_for, Blueprint
from werkzeug.utils import secure_filename
import os, datetime

 
from app.model import db, Book

 
from app.home import home_blueprint


 
@home_blueprint.route("/", endpoint="home")
def home():
    books = Book.query.all() 
    return render_template("home.html", books=books)

 

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}Library System{% endblock %}</title>
        <link
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            rel="stylesheet"
        />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous"
        />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('home.home') }}"
                >Library System</a
            >
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('home.home') }}"
                            >Home</a
                        >
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('books.create') }}"
                            >Add New Book</a
                        >
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container mt-4">
            {% block content %}
            <!-- Content will be injected here -->
            {% endblock %}
        </div>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

app/templates/book_detail.html
{% extends 'base.html' %}
<!--  -->
{% block title %}Book Details{% endblock %}
<!--  -->
{% block content %}
<main>
    <section>
        <div class="book-show">
            <div class="container py-5">
                <!--  -->
                <div class="content">
                    <div class="mb-3 d-flex justify-content-between">
                        <h2 class="">Book Info</h2>

                        <a
                            href="{{ url_for('books.list') }}"
                            class="btn btn-primary"
                        >
                            Back to all Books
                        </a>
                    </div>

                    <div class="">
                        <div class="row">
                            <div class="col-5">
                                <div class="h-100">
                                    <img
                                        src="{{ book.image_url }}"
                                        class="card-img-top w-100 h-100 object-cover"
                                        alt="{{ book.name }}"
                                    />
                                </div>
                            </div>

                            <div class="col-7">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <strong class="text-capitalize"
                                            >Name:
                                        </strong>
                                        {{book.name}}
                                    </h5>

                                    <p>
                                        <strong class="text-capitalize"
                                            >Image:
                                        </strong>
                                        {{book.image_url}}
                                    </p>

                                    <p class="card-text">
                                        <strong class="text-capitalize"
                                            >description:
                                        </strong>
                                        {{book.description}}
                                    </p>

                                    <div class="d-flex gap-5 mt-5">
                                        <a
                                            href="{{book.update_url}}"
                                            class="btn btn-success"
                                        >
                                            Update
                                        </a>

                                        <form
                                            action="{{ book.delete_url }}"
                                            method="POST"
                                        >
                                            <input
                                                type="submit"
                                                value="Delete"
                                                class="btn btn-danger"
                                            />
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--  -->
            </div>
        </div>
    </section>
</main>
{% endblock %}

app/templates/book_list.html
{% extends 'base.html' %} {% block title %}Library Books{% endblock %}

<!--  -->
{% block content %}
<main>
    <section>
        <div class="books">
            <div class="container py-5">
                <!--  -->
                <div class="content">
                    <div class="d-flex">
                        <div class="mb-3 me-3">
                            <a
                                href="{{ url_for('books.create') }}"
                                class="btn btn-primary"
                            >
                                Add New Book
                            </a>
                        </div>
                    </div>

                    <h2>All Books</h2>

                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Image</th>
                                <th>Show</th>

                                <th>Update</th>
                                <th>Delete</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for book in books %}
                            <tr>
                                <td>{{book.id}}</td>
                                <td>{{book.name}}</td>
                                <td>{{book.description }}</td>
                                <td>{{book.image}}</td>
                                <td>
                                    <a
                                        href="{{book.show_url}}"
                                        class="btn btn-info text-white"
                                    >
                                        Show
                                    </a>
                                </td>

                                <td>
                                    <a
                                        href="{{book.update_url}}"
                                        class="btn btn-success"
                                        >Update</a
                                    >
                                </td>
                                <td>
                                    <form
                                        action="{{ book.delete_url }}"
                                        method="POST"
                                    >
                                        <input
                                            type="submit"
                                            value="Delete"
                                            class="btn btn-danger"
                                        />
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--  -->
            </div>
        </div>
    </section>
</main>
{% endblock %}

app/templates/create_book.html
{% extends 'base.html' %} {% from 'bootstrap5/form.html' import render_form %}
{% block title %}Create New Book{% endblock %}

<!--  -->
{% block content %}
<main>
    <section>
        <div class="book-create">
            <div class="container py-5">
                <!--  -->
                <div class="content">
                    <div class="mb-5 d-flex justify-content-between">
                        <h2 class="">Add new Book</h2>

                        <a
                            href="{{ url_for('books.list') }}"
                            class="btn btn-primary"
                        >
                            Back to all Books
                        </a>
                    </div>

                    {{ render_form(form) }}
                </div>
                <!--  -->
            </div>
        </div>
    </section>
</main>
{% endblock %}

app/templates/edit_book.html
{% extends 'base.html' %} {% from 'bootstrap5/form.html' import render_form %}
{% block title %}Edit Book{% endblock %}

<!--  -->
{% block content %}
<main>
    <section>
        <div class="book-update">
            <div class="container py-5">
                <!--  -->
                <div class="content">
                    <div class="mb-5 d-flex justify-content-between">
                        <h2 class="">Update Book</h2>

                        <a
                            href="{{ url_for('books.list') }}"
                            class="btn btn-primary"
                        >
                            Back to all Books
                        </a>
                    </div>

                    {{ render_form(form) }}
                </div>
                <!--  -->
            </div>
        </div>
    </section>
</main>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %} {% block title %}Library Books{% endblock %}

<!--  -->
{% block content %}

<div>
    <div class="container">home page</div>
</div>
{% endblock %}